# -*- coding: utf-8 -*-
"""prj0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qheUx288xxND2akh1riRWDQdcwWzG9FF
"""

from traitlets.traitlets import List
from numpy.lib.shape_base import kron
import random
import matplotlib.pyplot as plt
import numpy as np

k = int(input("Input K: "))
list = [0] * k
xlist = ['0']*k
sum = 0
for i in range(k):
  xlist[i]=str(i+1)
for i in range(10):
    tmp = random.randint(1, k)
    print(tmp, end=" ")
    list[tmp-1] += 1
print()
for i in range(k):
    list[i]/=10
    sum+=list[i]
    print(list[i],end=" ")
    if(i!=k-1):
      print('+',end=" ")
    else:
      print('=',end=" ")
print(sum)
sum = 0
plt.bar(xlist,list)
plt.title('do 10')
plt.show()

for i in range(k):
    list[i]=0

for i in range(10000):
    tmp = random.randint(1, k)
    list[tmp-1] += 1

print()
for i in range(k):
    list[i]/=10000
    sum+=list[i]
    print(list[i],end=" ")
    if(i!=k-1):
      print('+',end=" ")
    else:
      print('=',end=" ")
print(sum)

plt.bar(xlist,list)
plt.title('do 10000')
plt.show()