# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FDUVzHXVPDnZolxV2Td8P2pCOrLg_j_d
"""

import numpy as np
import matplotlib.pyplot as plt

# Define parameters for the exponential distribution
lamda = int(input("지수분포 파라미터 : "))


def inv_exp(u, lamda):
    return -1/lamda*np.log(1-u)

samples = int(input("표본 수 : "))
U = np.random.uniform(size=samples)
X = inv_exp(U, lamda)

X_sorted = np.sort(X)

F_emp = np.arange(1, samples+1) / samples

plt.plot(X_sorted, F_emp, label='Empirical CDF')
plt.plot(X_sorted, 1-np.exp(-lamda*X_sorted), label='Exponential CDF')
plt.legend()
plt.show()