# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15RjgQKjXL1GzhnqfMzVtEfKxaSK3K1jn
"""

import random as radius

def func(x, y):
    x = (x-0.5)**2
    y = (y-0.5)**2
    if (x + y) <= 0.25:
        return 1
    else:
        return 0

n = int(input("시행 횟수를 입력하세요: "))
S = 0.0
for i in range(n):
    x = radius.random()
    y = radius.random()
    S += func(x, y)
print("trial : ", n)
print("Value of Sn:", S)
print("Value of Sn/n:", (S/n))
print("Value of Pi (4*Sn/n):", (S / n)*4)